[package]
name = "lumina"
version = "0.1.0"
edition = "2024"

[dependencies]
brightness = {version="0.5.0", default-features = false }
clap = { version = "4.5.39", features = [
  "derive",
  "wrap_help",
  "unstable-markdown",
] }
colored = "3.0.0"
